### ISSUE TITLE
vite重新编译生成空文件，其他地方有引用相关组件就会报错

### ISSUE THREAD

**Issue by ying-611** [fancn21th/xyzchat#5]
问题：
在web中引用了@rope/core中的组件，然后修改组件，出现报错

**Comment by ying-611** [comment]
在`vite.config.ts` 中的build配置项加入`emptyOutDir: false`
<img width="960" alt="企业微信截图_17176386443329" src="https://github.com/fancn21th/xyzchat/assets/71594654/b9a1b5f6-c5c3-4d34-9caf-0bd20ef34c8f">

**Comment by fancn21th** [comment]
pls try the newest ver.
